image: python:latest

stages:
  - package

verify:
  stage: package
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
  script:
    - python3 -m pip install twine setuptools wheel
    - python3 setup.py sdist bdist_wheel
    - twine check dist/*

package:
  stage: package
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - python3 -m pip install twine setuptools wheel
    - python3 setup.py sdist bdist_wheel
    - twine check dist/*
    - echo -e "[distutils]\nindex-servers = pypi\n\n[pypi]\nusername = __token__\npassword = ${PYPI_API_TOKEN}\n" >> ~/.pypirc
    - python3 -m twine upload dist/*
